dist: willy
language: python
python: "2.7"

before_install:
  # Make sure everything's up to date.
  - sudo apt-get update -qq

install:
  # Install Ansible.
  - pip install ansible==2.1.0

script:
  - ansible-playbook work.yml --syntax-check
  - ansible-playbook personal.yml --syntax-check
  - ansible-playbook work.yml --sudo
  - ansible-playbook personal.yml --sudo
