---
- hosts: localhost
  become: yes
  become_method: sudo
  roles:
    - { role: ppa, tags: [ 'work' ] }
    # - ppa
    # - common
    # - installable
#   antes instalar:
#   python-setuptools
#   python-pip
