---
    - name: download installer
      get_url:
        url="{{ item.value.url }}"
        dest="~/Downloads/{{ item.key }}"
        mode=0744
        validate_certs=False
      when: env_tag in item.value.when and 'url' in item.value
      with_dict: packages

    - name: extract the installer
      unarchive: src="~/Downloads/{{ item.key }}" dest=/usr/local/bin copy=no
      when: 'extractable' in item
      with_dict: packages

    - name: run deb installer
      apt:
        deb="~/Downloads/{{ item.key }}"
      when: env_tag in item.value.when and 'url' in item.value
      with_dict: packages
